on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - uses: actions/upload-artifact@v4
      with:
        name: plug-in
        path: community-rust-plugin/target/community-rust-plugin-*.jar
